### ISSUE TITLE
Error no POM file when build

### ISSUE THREAD

**Issue by minobug** [mdousek/unicenta#1]
Hi,
I have tried to build but got No POM file error. Do you have any idea? Thank you.

[http://paste.ofcode.org/pLUgGSgPK7dafei7a3AUXL](url)

**Comment by mdousek** [comment]
Hey minobug, the error message has your answer:

> there is no POM in this directory (C:\Windows). Please verify you invoked Maven from the correct directory

To run maven from the project root directory just cd into the right location and run mvn from the CLI or configure your Maven NetBeans plugin accordingly.

**Comment by minobug** [comment]
Hi Mdousek,

Thank you for your answer. 
I have the next question it's how i can config detail about Store, Saler tax ID and Certificate file and password etc? I  haven't seen  no where to do that.

Thank you.

**Comment by mdousek** [comment]
Hi minobug, 

First make sure you're building from the "eet" branch, not master.

Configure the EET parameters in the unicenta resource eet.properties, restart unicenta for the changes to take effect. 

If your instance of unicenta does not contain this resource already with placeholder values, create one with this name and use this as a template:
src/main/resources/com/openbravo/pos/templates/eet.properties
If your unicenta database was created

**Comment by minobug** [comment]
Hi Mdousek,

Sorry about reply this topic, i just want to ask if you provide custom work for your version? 

Thank you.
